[package]
name = "rust_swagger_validator"
version = "0.1.1"
authors = ["Samuele Maci <macisamuele@gmail.com>"]
publish = false
build = "rust/src/build.rs"

[lib]
path = "rust/src/lib.rs"
name = "rust_swagger_validator"
crate-type = ["rlib", "cdylib"]

[build-dependencies]
built = "^0.3"

[dependencies]
chrono = "*"

[dependencies.pyo3]
version = "*"
features = ["extension-module"]
