swagger: '2.0'
info:
  title: Test
paths:
  /endpoint:
    get:
      description: A get endpoint
      operationId: get_endpoint
      responses:
        default:
          description: A generic response
