# This configuration file is used by ${GIT_REPO_ROOT}/ci/ci-config.py
# to generate the CI configurations for appveryor, travis and circleCI
#
# The schema of this config file is defined on ${GIT_REPO_ROOT}/ci/config-schema.json
#
# The main objective of having this file defined here is to ensure that we do define our
# testing environments only once and having a tool that makes sure that we do run all of
# them on the supported CIs.
# It seems a lot of work for a small task, and probably that's true, but there is no
# (free) CI that allows to run tests on all platforms :(

testing_environments:
# Linting
- os: [linux]
  python: '3.6'
  env: {TOXENV: lint}
- os: [linux]
  python: '3.6'
  env: {TOXENV: coverage}
# Python and Rust testing and Wheels generation
- os: [linux, osx, windows]
  python: '2.7'
  env: {TOXENV: 'cargo_test,py27,py27-wheel'}
- os: [linux, osx, windows]
  python: '3.5'
  env: {TOXENV: 'cargo_test,py35,py35-wheel'}
- os: [linux, osx, windows]
  python: '3.6'
  env: {TOXENV: 'cargo_test,py36,py36-wheel'}
- os: [linux, osx, windows]
  python: '3.7'
  env: {TOXENV: 'cargo_test,py37,py37-wheel'}
